---
- hosts: servers
  tasks:
  - name: creating file 
    file:
     path: /tmp/custom-playbook.sh
     owner: ansible
     mode: 777
     state: touch
  - name:
    file:
     path: /tmp/ansible-dir
     owner: ansible
     mode: 666
     state: mkdir
...
