---
- hosts: servers
  tasks:
  - name: installing httpd 
    yum:
     name: httpd
     state: latest
     notify:
     - name: starting httpd
  handlers:
  - name: starting httpd
    service:
     name: httpd
     state: started

...
 
 