---
- hosts: servers
  tasks:
  - name: installing httpd 
    yum:
     name: httpd
     state: latest
     notify:
      - starting httpd
  handlers:
  - name: starting httpd
    service:
     name: httpd
     state: restarted

...
 
 